# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-nbdev-from-empty',
                'doc_host': 'https://Mjboothaus.github.io',
                'git_url': 'https://github.com/Mjboothaus/test-nbdev-from-empty',
                'lib_path': 'test_nbdev_from_empty'},
  'syms': {'test_nbdev_from_empty.core': {'test_nbdev_from_empty.core.foo': ('core.html#foo', 'test_nbdev_from_empty/core.py')}}}